ALTER TABLE "public"."account_types" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."accounts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."household_members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."households" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."transactions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."budget_allocations" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read access to all users" ON "public"."account_types" FOR SELECT USING (true);
CREATE POLICY "Allow household members to read accounts" ON "public"."accounts" FOR SELECT USING ("public"."is_household_member"("household_id"));
CREATE POLICY "Allow household members to manage accounts" ON "public"."accounts" FOR ALL USING ("public"."is_household_member"("household_id"));
CREATE POLICY "Allow household members to read categories" ON "public"."categories" FOR SELECT USING ("public"."is_household_member"("household_id"));
CREATE POLICY "Allow household members to manage categories" ON "public"."categories" FOR ALL USING ("public"."is_household_member"("household_id"));
CREATE POLICY "Allow member to read household members" ON "public"."household_members" FOR SELECT USING ("public"."is_household_member"("household_id"));
CREATE POLICY "Allow owner to manage household members" ON "public"."household_members" FOR ALL USING ("public"."is_household_owner"("household_id")) WITH CHECK ("public"."is_household_owner"("household_id"));
CREATE POLICY "Allow member to read households" ON "public"."households" FOR SELECT USING ("public"."is_household_member"("id"));
CREATE POLICY "Allow owner to manage households" ON "public"."households" FOR ALL USING ("public"."is_household_owner"("id"));
CREATE POLICY "Allow household members to read transactions" ON "public"."transactions" FOR SELECT USING ("public"."is_household_member"("household_id"));
CREATE POLICY "Allow household members to manage transactions" ON "public"."transactions" FOR ALL USING ("public"."is_household_member"("household_id"));
CREATE POLICY "Allow all users to read user info" ON "public"."users" FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON "public"."users" FOR INSERT WITH CHECK (("auth"."uid"() = "id"));
CREATE POLICY "Users can update own profile." ON "public"."users" FOR UPDATE USING (("auth"."uid"() = "id"));
CREATE POLICY "Allow household members to read budget allocations" ON "public"."budget_allocations" FOR SELECT USING ("public"."is_household_member"("household_id"));
CREATE POLICY "Allow household members to create and update budget allocations" ON "public"."budget_allocations" FOR INSERT WITH CHECK ("public"."is_household_member"("household_id"));
CREATE POLICY "Allow household members to update budget allocations" ON "public"."budget_allocations" FOR UPDATE USING ("public"."is_household_member"("household_id"));
CREATE POLICY "Allow household owners to delete budget allocations" ON "public"."budget_allocations" FOR DELETE USING ("public"."is_household_owner"("household_id")); 